### ISSUE TITLE
R-version requirement

### ISSUE THREAD

**Issue by strengejacke** [bbolker/broom.mixed#50]
Is there a reason (e.g. a specific function...) why _broom.mixed_ depends on R >= 3.5? There are still a lot of people around who have R 3.3.x or 3.4.x (or maybe < 3.3) installed, which makes it difficult to import _broom.mixed_ into own packages if you want to reach as many users as possible...

You can close this issue if it's necessary to depend on R >= 3.5, else, could the version requirement be decreased?

**Comment by bbolker** [comment]
This was added in e7010da9bcb because I saved the test files in the new serialization version.  I should be able to address this by (1) storing in the old version (2) modifying the tests that use stored data (most of them) to be run conditional on a newer version.

**Comment by bbolker** [comment]
Ugh. Forgot that I needed to *install* the newest version before rebuilding (because the scripts for running/saving examples are retrieved from `system.file(...)`, so the version that's found is that of the latest *installed* version ...

**Comment by bbolker** [comment]
should be resolved now.  I gave up trying to test on oldrelease on travis, but current version passes win-builder/R-oldrelease with NOTEs, so I'm going to suppose it works/will continue working on older versions until I hear otherwise.

Next question is how much of a priority this is to push to CRAN.  Only about 5 weeks since last CRAN release, so arguably this should wait a month or so, depending on how one interprets  “no more than every 1–2 months” from the CRAN policy ...

**Comment by strengejacke** [comment]
I don't think you need to push an update to CRAN this year, at least not for this issue. But once it's released on CRAN, I can import broom.mixed in my packages.

Will `broom::tidy()` automatically select the correct tidiers from **broom.mixed** for mixed models, or will `broom.mixed::tidy()` call `broom::tidy()` for non-mixed models? I think this is related to https://github.com/bbolker/broom.mixed/issues/23 and would make things easier, so package-developers don't have to check if an object is suitable for **broom** or **broom.mixed**.

**Comment by bbolker** [comment]
I don't know. I think this would best be handled from the `broom` side, partly because I'm lazy and partly because I don't quite know how to engineer this properly.  I could imagine `broom` keeping an up-to-date list of classes handled by `broom.mixed` and constructing stub methods that either (1) issue an error message suggesting the user install `broom.mixed` (if it's not installed) or (2) load `broom.mixed` (if not loaded) and pass the object to the `broom.mixed` method ... Maybe raise this as an issue on the `broom` repo ... ??

**Comment by strengejacke** [comment]
> Maybe raise this as an issue on the broom repo ... ??

Ok, I will do.
